"""Stage 4 — enrich PlasticItem with polymer type, harmful flag, recyclability.

Banned-state list is a placeholder. Replace by loading data/epa_banned.json
once Firecrawl scrape job has run (apps/analytics/.../firecrawl_jobs.py).
"""
from __future__ import annotations
import json
from pathlib import Path
from snaptrash_common.schemas import PlasticItem
from snaptrash_common.env import REPO_ROOT

# ASTM D7611 resin identification codes (RIC)
RESIN_TO_POLYMER = {1: "PET", 2: "HDPE", 3: "PVC", 4: "LDPE", 5: "PP", 6: "PS", 7: "Other"}

# Widely recyclable (MRF-accepted) per EPA 2022 MSW report
RECYCLABLE = {"PET", "HDPE", "PP"}

# Harmful: PVC releases dioxins on combustion (WHO 2021); PS leaches styrene (IARC Group 2B); PC contains BPA
HARMFUL = {"PVC", "PS", "PC"}

# Fallback if data/epa_banned.json missing — CA-only subset (SB-54 + SB-270)
# Full multi-state data lives in data/epa_banned.json (generated by Firecrawl job)
DEFAULT_BANNED = {
    "PS": ["CA", "NY", "ME"],
    "LDPE": ["CA", "NY", "ME"],
}

_banned_cache: dict | None = None


def _banned_map() -> dict:
    global _banned_cache
    if _banned_cache is not None:
        return _banned_cache
    p = REPO_ROOT / "data" / "epa_banned.json"
    if p.exists():
        try:
            _banned_cache = json.loads(p.read_text())
            return _banned_cache
        except Exception:
            pass
    _banned_cache = DEFAULT_BANNED
    return _banned_cache


def _infer_polymer(item: PlasticItem) -> str:
    if item.resin_code and item.resin_code in RESIN_TO_POLYMER:
        return RESIN_TO_POLYMER[item.resin_code]
    t = item.type.lower()
    if "foam" in t or "styrofoam" in t:
        return "PS"
    if "bottle" in t or "pet" in t:
        return "PET"
    if "bag" in t or "wrap" in t or "cling" in t:
        return "LDPE"
    if "container" in t and "clear" in t:
        return "PET"
    return "Other"


def enrich(item: PlasticItem, *, state: str = "CA") -> PlasticItem:
    polymer = _infer_polymer(item)
    item.polymer_type = polymer

    banned_states = _banned_map().get(polymer, [])
    is_banned = state in banned_states
    item.recyclable = polymer in RECYCLABLE and not item.is_black_plastic
    item.harmful = polymer in HARMFUL or item.is_black_plastic

    if is_banned:
        item.status = f"banned_{state}"
        item.alert = f"{polymer} {item.type} banned in {state}. Switch to PET clamshell."
    elif item.harmful:
        item.status = "harmful"
        item.alert = f"{polymer} releases harmful additives. Avoid."
    elif item.recyclable:
        item.status = "recyclable"
    else:
        item.status = "non_recyclable"
    return item


def compute_sustainability_metrics(
    plastic_items: list[PlasticItem], state: str = "CA"
) -> dict:
    """Compute ban_flag_count, recyclable_count, total_plastic_kg etc. for sustainability score.
    Must be called *after* enrich() so that polymer_type, recyclable, harmful are populated.
    Matches exact signals from SnapTrash sustainability spec.
    """
    if not plastic_items:
        return {
            "total_plastic_kg": 0.0,
            "ban_flag_count": 0,
            "recyclable_count": 0,
            "total_plastic_count": 0,
            "harmful_count": 0,
        }

    total_plastic_kg = sum(p.estimated_kg for p in plastic_items)
    total_plastic_count = sum(p.estimated_count for p in plastic_items)
    
    ban_flag_count = 0
    recyclable_count = 0
    harmful_count = 0
    
    for p in plastic_items:
        if not getattr(p, "polymer_type", None):
            continue
        poly = p.polymer_type
        item_type_lower = p.type.lower()
        
        # Banned plastics (CA law per spec): PS or LDPE single-use bags
        is_bag = any(b in item_type_lower for b in ["bag", "shopping bag", "ldpe bag"])
        if poly == "PS" or (poly == "LDPE" and is_bag):
            ban_flag_count += p.estimated_count
        
        if getattr(p, "recyclable", False):
            recyclable_count += p.estimated_count
        
        if getattr(p, "harmful", False):
            harmful_count += p.estimated_count
    
    return {
        "total_plastic_kg": round(total_plastic_kg, 3),
        "ban_flag_count": ban_flag_count,
        "recyclable_count": recyclable_count,
        "total_plastic_count": total_plastic_count,
        "harmful_count": harmful_count,
    }
